version: '3'

services:

  logstash:
    command: /usr/share/plugins/plugin/.ci/logstash-run.sh
    build:
      args:
        - ELASTIC_STACK_VERSION=$ELASTIC_STACK_VERSION
        - DISTRIBUTION=${DISTRIBUTION:-default}
        - DISTRIBUTION_SUFFIX=${DISTRIBUTION_SUFFIX}
    environment:
      - DISTRIBUTION=${DISTRIBUTION:-default}
      - DISTRIBUTION_SUFFIX=${DISTRIBUTION_SUFFIX}
      - INTEGRATION=${INTEGRATION:-false}
      - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}
    depends_on:
      - enterprise_search

  elasticsearch:
    build:
      context: ../
      dockerfile: .ci/Dockerfile.elasticsearch
      args:
        - ELASTIC_STACK_VERSION=$ELASTIC_STACK_VERSION
        - DISTRIBUTION_SUFFIX=${DISTRIBUTION_SUFFIX}
    user: elasticsearch
    environment:
      - cluster.name=es-cluster
      - node.name=es-node
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.license.self_generated.type=trial
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  enterprise_search:
    build:
      context: ../
      dockerfile: .ci/Dockerfile.enterprise_search
      args:
        - ELASTIC_ENTERPRISE_SEARCH_VERSION=$ELASTIC_STACK_VERSION
        - DISTRIBUTION_SUFFIX=${DISTRIBUTION_SUFFIX}
    environment:
      - elasticsearch.host=http://elasticsearch:9200
      - elasticsearch.password=password
      - elasticsearch.startup_retry.interval=30
      - ENT_SEARCH_DEFAULT_PASSWORD=password
      - secret_management.encryption_keys=[changeme]
      - allow_es_settings_modification=true
      - ent_search.ssl.enabled=${SECURE_INTEGRATION:-false}
      - ent_search.ssl.keystore.path=/certificates/root_keystore.jks
      - ent_search.ssl.keystore.password=changeme
    volumes:
      - ../spec/fixtures/certificates:/certificates
    ports:
      - "3002:3002"
    depends_on:
      - elasticsearch